replicaCount: 1

image:
  repository: "pinkmelon/api-gateway-hrd"
  tag: 21

service:
  type: LoadBalancer
  port: 80 # Service port exposed to Ingress
  targetPort: 9100 # Pod/container port

revisionHistoryLimit: 3

configMapName: api-gateway-config
