apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "api-gateway-cluster-issuer"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

    # --- REQUIRED for SockJS & STOMP ----
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/upgrade: "websocket"
    nginx.ingress.kubernetes.io/connection: "upgrade"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

    # Allow WebSocket fallback transports (long polling, xhr_streaming)
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Chart.Name }}"

spec:
  ingressClassName: nginx
  rules:
    - host: gate-way.hrdportal.systems
      http:
        paths:

          # ðŸ”¥ SockJS requires ALL /ws/** paths
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}

          # normal REST API
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}

  tls:
    - hosts:
        - gate-way.hrdportal.systems
      secretName: {{ .Chart.Name }}-tls
